### PR TITLE
Normalize XBIC by US_IC

### PR DESCRIPTION
**Pull request by dnzckn**
XBIC should be normalized by US_IC

### CODE REVIEW

**Comment by rekumar** [comment]
Problem with this approach is that the absolute value of current will be totally wrong after dividing by USIC. Should try to preserve the absolute XBIC signal as best as possible. Something like:

```
norm_factor = usic/np.nanmean(usic)
xbic = xbic/norm_factor
```

Also, since you've figured out how, can you integrate the quantification step to convert XBIC counts to some known units? Pretty sure the amplifier settings are present in the h5 file.

**Comment by dnzckn** [comment]
Yeah I brought up the same issue in beamline chat, this normalization makes the units Current/us_ic which is no longer Amps. 

The equation to convert from XBIC signal to Amps is as the following:
```
V_sens = 5 /1e7 
ds_ic = maps['xbic']
Amp_gain = A/V  #(typically in µA/V)
V_sens * ds_ic * Amp_gain = Measured Current
```

I digged around in the .h5 scan file using `silx view` but wasn't able to any saved value for the ds_ic's Amp_gain setting. I'll email Grace if she knows the location for this, or if it can be implemented in the future. 

Currently in my analysis the way I am handling this is by saving Amp_gain setting to a lookup table from run notes.

We can simply introduce another variable to preserve the raw XBIC counts before normalization.

**Comment by dnzckn** [comment]
bump

**Comment by rekumar** [comment]
have you added in an option to scale XBIC counts yet?

**Comment by dnzckn** [comment]
see line 86 & 92 in latest version
@rekumar

**Pull request closed without merging**
